In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('customer.csv').drop(columns=['age', 'gender'])

In [3]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [4]:
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

### 1. Ordinal Encoding

In [5]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:2], df.iloc[:,-1], test_size=0.2)

In [6]:
X_train.head()

,review,education
9,Good,UG
34,Average,School
17,Poor,UG
19,Poor,PG
41,Good,PG


In [7]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [8]:
X_train = oe.fit_transform(X_train) #.fit_transform() 1st see data, undertand it then transform 
X_test = oe.transform(X_test)

In [9]:
X_train

array([[2., 1.],
       [1., 0.],
       [0., 1.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [1., 2.],
       [1., 2.],
       [1., 0.],
       [0., 2.],
       [1., 1.],
       [1., 0.],
       [2., 0.],
       [1., 0.],
       [1., 1.],
       [2., 1.],
       [0., 1.],
       [1., 1.],
       [1., 2.],
       [2., 0.],
       [2., 1.],
       [0., 2.],
       [2., 2.],
       [2., 0.],
       [2., 2.],
       [0., 2.],
       [0., 2.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [2., 1.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [2., 1.]])

#### Some Functions & Methods

In [10]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [11]:
oe.feature_names_in_

array(['review', 'education'], dtype=object)

In [12]:
oe.n_features_in_ #number of fectures that u work 

2

In [13]:
oe.inverse_transform(np.array([0,2]).reshape(1,2)) #convert into 2D
# .inverse_transform() - convert numeric values into categorical values

array([['Poor', 'PG']], dtype=object)

In [14]:
oe.get_feature_names_out() # kis features pe of ordinal encoding apply kiya h  

array(['review', 'education'], dtype=object)

#### Handle unknown values

**Method 1** - Through error

In [15]:
oe.transform(np.array(['Poor', 'College']).reshape(1,2)) 

c:\Users\hritik\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


ValueError: Found unknown categories ['College'] in column 1 during transform

**Method 2**- there are some **hyper parameter**<br>
handle_unknown = 'use_encoded_value', <br>
unknown_value = -1

In [16]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']], 
                   handle_unknown='use_encoded_value', 
                   unknown_value=-1, dtype=int)

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:2], df.iloc[:,-1], test_size=0.2)
X_train = oe.fit_transform(X_train)
oe.transform(np.array(['Poor', 'College']).reshape(1,2)) 

c:\Users\hritik\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[ 0, -1]])

### To handling infrequent categories

In [17]:
X = np.array([['dog'] * 5 + ['cat'] * 20 + ['rabbit'] * 10 + ['snake'] * 3 + ['horse'] * 2], dtype=object).T

In [18]:
X

array([['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['dog'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['cat'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['rabbit'],
       ['snake'],
       ['snake'],
       ['snake'],
       ['horse'],
       ['horse']], dtype=object)

1st approch

In [19]:
enc = OrdinalEncoder(max_categories=3).fit(X)
# it will make only 3 categories and short them according to there values(best example in copy)

To see the infrequent categories

In [20]:
enc.infrequent_categories_

[array(['dog', 'horse', 'snake'], dtype=object)]

In [21]:
enc.transform(np.array([['cat', 'rabbit', 'snake', 'dog', 'horse']]).reshape(5,1))

array([[0.],
       [1.],
       [2.],
       [2.],
       [2.]])

Better way <br>
2nd approch

In [22]:
enc = OrdinalEncoder(min_frequency=4).fit(X)
enc.infrequent_categories_

[array(['horse', 'snake'], dtype=object)]

In [23]:
enc.transform(np.array([['cat', 'rabbit', 'dog','snake', 'horse']]).reshape(5,1))

array([[0.],
       [2.],
       [1.],
       [3.],
       [3.]])

### Handling Missing 

In [24]:
data = [['cat'], [np.nan], ['dog'], ['fish'], [np.nan]]

encoder = OrdinalEncoder(encoded_missing_value=np.nan)

encoded_data = encoder.fit_transform(data)

print(encoded_data)

[[ 0.]
 [nan]
 [ 1.]
 [ 2.]
 [nan]]


### 2. Label Encoding

In [25]:
df.head()

,review,education,purchased
0,Average,School,No
1,Poor,UG,No
2,Good,PG,No
3,Good,PG,No
4,Average,UG,No


In [26]:
df['purchased'].sample(10) #output data

44     No
26     No
12     No
11    Yes
15     No
31    Yes
2      No
43     No
42    Yes
7     Yes
Name: purchased, dtype: object

In [27]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:2], df.iloc[:,-1], test_size=0.2)

In [28]:
from sklearn.preprocessing import LabelEncoder 

In [29]:
le = LabelEncoder() #object
y_train = le.fit_transform(y_train)
y_test = le.transform(y_test)

In [30]:
le.classes_ #to check

array(['No', 'Yes'], dtype=object)

In [31]:
le.inverse_transform(np.array([1,1,0]))

array(['Yes', 'Yes', 'No'], dtype=object)

### 3. One Hot Encoding

In [32]:
cars = pd.read_csv('cars.csv').drop(columns=['km_driven', 'owner'])
cars.head()

,brand,fuel,selling_price
0,Maruti,Diesel,450000
1,Skoda,Diesel,370000
2,Honda,Petrol,158000
3,Hyundai,Diesel,225000
4,Maruti,Petrol,130000


In [33]:
X = cars.iloc[:, :2]
y = cars.iloc[:, -1]

In [34]:
from sklearn.model_selection import train_test_split

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42) 

In [36]:
X_train.head()

,brand,fuel
6518,Tata,Petrol
6144,Honda,Petrol
6381,Hyundai,Diesel
438,Maruti,Diesel
5939,Maruti,Petrol


In [37]:
# way 36 columns
X_train['brand'].nunique() #32
X_train['fuel'].nunique() #4

4

In [38]:
from sklearn.preprocessing import OneHotEncoder

In [39]:

ohe = OneHotEncoder(sparse_output=False, dtype=np.int32)

In [40]:
X_train = ohe.fit_transform(X_train) #to see the sparse matrix

In [41]:
X_train

array([[0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 1],
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 0, 1]])

In [42]:
X_train.shape

(6502, 36)

In [43]:
ohe.categories_

[array(['Ambassador', 'Ashok', 'Audi', 'BMW', 'Chevrolet', 'Daewoo',
        'Datsun', 'Fiat', 'Force', 'Ford', 'Honda', 'Hyundai', 'Isuzu',
        'Jaguar', 'Jeep', 'Kia', 'Land', 'Lexus', 'MG', 'Mahindra',
        'Maruti', 'Mercedes-Benz', 'Mitsubishi', 'Nissan', 'Opel',
        'Peugeot', 'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen',
        'Volvo'], dtype=object),
 array(['CNG', 'Diesel', 'LPG', 'Petrol'], dtype=object)]

In [44]:
ohe.n_features_in_

2

In [45]:
ohe.feature_names_in_

array(['brand', 'fuel'], dtype=object)

In [46]:
ohe.get_feature_names_out()

array(['brand_Ambassador', 'brand_Ashok', 'brand_Audi', 'brand_BMW',
       'brand_Chevrolet', 'brand_Daewoo', 'brand_Datsun', 'brand_Fiat',
       'brand_Force', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Isuzu', 'brand_Jaguar', 'brand_Jeep', 'brand_Kia',
       'brand_Land', 'brand_Lexus', 'brand_MG', 'brand_Mahindra',
       'brand_Maruti', 'brand_Mercedes-Benz', 'brand_Mitsubishi',
       'brand_Nissan', 'brand_Opel', 'brand_Peugeot', 'brand_Renault',
       'brand_Skoda', 'brand_Tata', 'brand_Toyota', 'brand_Volkswagen',
       'brand_Volvo', 'fuel_CNG', 'fuel_Diesel', 'fuel_LPG',
       'fuel_Petrol'], dtype=object)

In [47]:

X_train_encoded = ohe.fit_transform(X_train)

In [48]:
X_train_encoded.shape

(6502, 72)

In [49]:
# to convert this array into pandas dataframe

pd.DataFrame(X_train_encoded, columns=ohe.get_feature_names_out())

,x0_0,x0_1,x1_0,x1_1,x2_0,x2_1,x3_0,x3_1,x4_0,x4_1,...,x31_0,x31_1,x32_0,x32_1,x33_0,x33_1,x34_0,x34_1,x35_0,x35_1
0,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,1,0,1,0,0,1
1,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,1,0,1,0,0,1
2,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,0,1,1,0,1,0
3,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,0,1,1,0,1,0
4,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,1,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6497,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,0,1,1,0,1,0
6498,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,0,1,1,0,1,0
6499,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,1,0,1,0,0,1
6500,1,0,1,0,1,0,1,0,1,0,...,1,0,1,0,0,1,1,0,1,0


### Drop

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

ohe = OneHotEncoder(drop='first', sparse_output=False) #drop the first col.
ohe.fit_transform(X_train).shape

(6502, 34)

In [ ]:
#[1st cate. of X_train col,  2nd cate. of X_test col] thats way out of 36 -> 34
ohe.drop_idx_ 

array([0, 0], dtype=object)

In [60]:
# Handling rare categories
X_train['brand'].value_counts()

brand
Maruti           1953
Hyundai          1127
Mahindra          635
Tata              586
Toyota            391
Honda             369
Ford              320
Chevrolet         185
Renault           183
Volkswagen        154
BMW                96
Skoda              82
Nissan             62
Jaguar             59
Volvo              54
Datsun             48
Mercedes-Benz      43
Fiat               35
Audi               30
Jeep               26
Lexus              22
Mitsubishi         13
Force               6
Land                5
Kia                 4
Ambassador          3
MG                  3
Daewoo              3
Isuzu               2
Ashok               1
Peugeot             1
Opel                1
Name: count, dtype: int64

In [59]:
X_train['fuel'].value_counts()

fuel
Diesel    3545
Petrol    2880
CNG         46
LPG         31
Name: count, dtype: int64

In [ ]:
# using min frequency

ohe = OneHotEncoder(sparse_output=False, min_frequency=100)
ohe.fit_transform(X_train).shape

(6502, 14)

In [58]:
ohe.get_feature_names_out()

array(['brand_Chevrolet', 'brand_Ford', 'brand_Honda', 'brand_Hyundai',
       'brand_Mahindra', 'brand_Maruti', 'brand_Renault', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_Diesel', 'fuel_Petrol', 'fuel_infrequent_sklearn'],
      dtype=object)

In [62]:
# using max_categories

ohe = OneHotEncoder(sparse_output=False,handle_unknown='ignore' ,max_categories=15)
ohe.fit_transform(X_train).shape

(6502, 19)

In [64]:
ohe.get_feature_names_out()

array(['brand_BMW', 'brand_Chevrolet', 'brand_Ford', 'brand_Honda',
       'brand_Hyundai', 'brand_Jaguar', 'brand_Mahindra', 'brand_Maruti',
       'brand_Nissan', 'brand_Renault', 'brand_Skoda', 'brand_Tata',
       'brand_Toyota', 'brand_Volkswagen', 'brand_infrequent_sklearn',
       'fuel_CNG', 'fuel_Diesel', 'fuel_LPG', 'fuel_Petrol'], dtype=object)

In [ ]:
# how to handle unknown category [through error]
ohe = OneHotEncoder(drop='first' ,sparse_output=False)
ohe.fit_transform(X_train)

ohe.transform(np.array(['local', 'Petrol']).reshape(1,2))

c:\Users\hritik\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


ValueError: Found unknown categories ['local'] in column 0 during transform

In [66]:
# ignore the new input
ohe = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
ohe.fit_transform(X_train)

ohe.transform(np.array(['local', 'Petrol']).reshape(1,2))

c:\Users\hritik\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1.]])

In [ ]:
ohe.inverse_transform(np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
                                0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
                                0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 
                                0., 0.,0., 0., 0., 1.]).reshape(1,36))

array([[None, 'Petrol']], dtype=object)

### 4. LabelBinarizer

In [ ]:
from sklearn.preprocessing import LabelBinarizer

# Sample target variables for a multi-class classsification problem
y = ['cat', 'dog', 'fish', 'dog', 'cat']

# Initialize the LabelBinarizer
lb = LabelBinarizer()

# Fit and transform the target variables
y_binarized = lb.fit_transform(y)

print('Binarized Labels:\n', y_binarized)

# Inverse transform to recover Original Labels
y_original = lb.inverse_transform(y_binarized)

print('Original Labels:\n', y_original)

Binarized Labels:
 [[1 0 0]
 [0 1 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]]
Original Labels:
 ['cat' 'dog' 'fish' 'dog' 'cat']


###  5. MultiLabelBinarizer

In [75]:
from sklearn.preprocessing import MultiLabelBinarizer

# example multi-label data
y = [('red', 'blue'), ('blue', 'green'), ('green',), ('red',)]

# Initialize MultiLabelBinarizer
mlb = MultiLabelBinarizer()

# fit and transform the data to Binary matrix
y_mlb = mlb.fit_transform(y)

print('Binary matrix:\n', y_mlb)
print('Class labels:', mlb.classes_)

# Inverse transform to recover original labels 
y_inv = mlb.inverse_transform(y_mlb)
print('Inverse transform labels:\n', y_inv)

Binary matrix:
 [[1 0 1]
 [1 1 0]
 [0 1 0]
 [0 0 1]]
Class labels: ['blue' 'green' 'red']
Inverse transform labels:
 [('blue', 'red'), ('blue', 'green'), ('green',), ('red',)]
